language: node_js

node_js:
  - 0.10.40

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam
  - npm install -g coffee-script@1.8.0
  - npm install -g https://github.com/practicalmeteor/spacejam/tarball/master coveralls

script:
    # Unit test using mocha
  - spacejam test            --loglevel debug --driver-package=practicalmeteor:mocha-console-runner --coverage
    # Integration test using mocha
  - spacejam test --full-app --loglevel debug --driver-package=practicalmeteor:mocha-console-runner --coverage && cat lcov.info | coveralls
    # Package test using mocha
  - spacejam test-packages   --loglevel debug --driver-package=practicalmeteor:mocha-console-runner --coverage
    # Package test using tinytest
  - spacejam test-packages   --loglevel debug --coverage
    # Package test using tinytest creates a coverage file with wrong path ?
  - cat lcov.info
