language: node_js

node_js:
  - 0.10.43

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

  # Install spacejam
  - npm install -g https://github.com/serut/spacejam/tarball/windows-suppport-rc4

script:
  - echo "BEGIN spacejam test"
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test            --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - echo "END spacejam test"


  - echo "BEGIN spacejam test --full-app"
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - echo "END spacejam test --full-app"


  - echo "BEGIN spacejam test-packages mocha"
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - spacejam test-packages   --driver-package practicalmeteor:mocha-console-runner --loglevel debug
  - echo "END spacejam test-packages mocha"

  - echo "BEGIN spacejam test-packages"
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - spacejam test-packages    --loglevel debug
  - echo "END spacejam test-packages"
